# Generated by Django 5.0.1 on 2024-01-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImgApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleimgmodel',
            name='file',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
