# Generated by Django 5.0.1 on 2024-01-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImgApp', '0003_alter_multipleimgmodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleimgmodel',
            name='file',
            field=models.FileField(upload_to='images/', verbose_name='documents'),
        ),
    ]
